# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='YYProto.proto',
  package='',
  serialized_pb='\n\rYYProto.proto\"x\n\x07YYProto\x12\x0b\n\x03\x63md\x18\x01 \x02(\x05\x12 \n\x07key_req\x18\x02 \x01(\x0b\x32\x0f.ExchangeKeyReq\x12 \n\x07key_ack\x18\x03 \x01(\x0b\x32\x0f.ExchangeKeyAck\x12\x1c\n\tlogin_req\x18\x08 \x01(\x0b\x32\t.LoginReq\"-\n\x0e\x45xchangeKeyReq\x12\n\n\x02\x66\x31\x18\x01 \x02(\x0c\x12\x0f\n\x07rsa_key\x18\x02 \x02(\x0c\"E\n\x0e\x45xchangeKeyAck\x12\n\n\x02\x66\x31\x18\x01 \x02(\x05\x12\x0f\n\x07rsa_key\x18\x02 \x02(\x0c\x12\n\n\x02\x66\x33\x18\x03 \x02(\x05\x12\n\n\x02\x66\x34\x18\x04 \x02(\x05\"\xef\x01\n\x08LoginReq\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\x0c\n\x04imei\x18\x03 \x02(\t\x12\n\n\x02\x66\x34\x18\x04 \x01(\t\x12\n\n\x02\x66\x35\x18\x05 \x01(\t\x12\n\n\x02\x66\x36\x18\x06 \x01(\t\x12\n\n\x02\x66\x37\x18\x07 \x01(\t\x12\n\n\x02\x66\x38\x18\x08 \x01(\t\x12\x0e\n\x06yymand\x18\t \x02(\t\x12\x13\n\x0bproxy_proto\x18\n \x02(\t\x12\x0b\n\x03\x66\x31\x31\x18\x0b \x01(\t\x12\x0b\n\x03\x66\x31\x32\x18\x0c \x02(\x08\x12\x0b\n\x03\x66\x31\x33\x18\r \x01(\t\x12\x0f\n\x07version\x18\x0e \x02(\t\x12\x0b\n\x03\x66\x31\x35\x18\x0f \x02(\x08\x12\x0b\n\x03\x66\x31\x36\x18\x10 \x02(\x08\"6\n\x0cHeartBeatAct\x12\x0b\n\x03\x63md\x18\x01 \x02(\x05\x12\x19\n\x02\x66\x37\x18\x07 \x01(\x0b\x32\r.ChallengeAct\"\x1b\n\x0c\x43hallengeAct\x12\x0b\n\x03key\x18\x03 \x01(\x0c')




_YYPROTO = descriptor.Descriptor(
  name='YYProto',
  full_name='YYProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='YYProto.cmd', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key_req', full_name='YYProto.key_req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key_ack', full_name='YYProto.key_ack', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='login_req', full_name='YYProto.login_req', index=3,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=137,
)


_EXCHANGEKEYREQ = descriptor.Descriptor(
  name='ExchangeKeyReq',
  full_name='ExchangeKeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='f1', full_name='ExchangeKeyReq.f1', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rsa_key', full_name='ExchangeKeyReq.rsa_key', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=184,
)


_EXCHANGEKEYACK = descriptor.Descriptor(
  name='ExchangeKeyAck',
  full_name='ExchangeKeyAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='f1', full_name='ExchangeKeyAck.f1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rsa_key', full_name='ExchangeKeyAck.rsa_key', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f3', full_name='ExchangeKeyAck.f3', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f4', full_name='ExchangeKeyAck.f4', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=255,
)


_LOGINREQ = descriptor.Descriptor(
  name='LoginReq',
  full_name='LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='username', full_name='LoginReq.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='LoginReq.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='imei', full_name='LoginReq.imei', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f4', full_name='LoginReq.f4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f5', full_name='LoginReq.f5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f6', full_name='LoginReq.f6', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f7', full_name='LoginReq.f7', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f8', full_name='LoginReq.f8', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='yymand', full_name='LoginReq.yymand', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='proxy_proto', full_name='LoginReq.proxy_proto', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f11', full_name='LoginReq.f11', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f12', full_name='LoginReq.f12', index=11,
      number=12, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f13', full_name='LoginReq.f13', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='LoginReq.version', index=13,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f15', full_name='LoginReq.f15', index=14,
      number=15, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f16', full_name='LoginReq.f16', index=15,
      number=16, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=258,
  serialized_end=497,
)


_HEARTBEATACT = descriptor.Descriptor(
  name='HeartBeatAct',
  full_name='HeartBeatAct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='HeartBeatAct.cmd', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f7', full_name='HeartBeatAct.f7', index=1,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=499,
  serialized_end=553,
)


_CHALLENGEACT = descriptor.Descriptor(
  name='ChallengeAct',
  full_name='ChallengeAct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='ChallengeAct.key', index=0,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=555,
  serialized_end=582,
)

_YYPROTO.fields_by_name['key_req'].message_type = _EXCHANGEKEYREQ
_YYPROTO.fields_by_name['key_ack'].message_type = _EXCHANGEKEYACK
_YYPROTO.fields_by_name['login_req'].message_type = _LOGINREQ
_HEARTBEATACT.fields_by_name['f7'].message_type = _CHALLENGEACT
DESCRIPTOR.message_types_by_name['YYProto'] = _YYPROTO
DESCRIPTOR.message_types_by_name['ExchangeKeyReq'] = _EXCHANGEKEYREQ
DESCRIPTOR.message_types_by_name['ExchangeKeyAck'] = _EXCHANGEKEYACK
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['HeartBeatAct'] = _HEARTBEATACT
DESCRIPTOR.message_types_by_name['ChallengeAct'] = _CHALLENGEACT

class YYProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _YYPROTO
  
  # @@protoc_insertion_point(class_scope:YYProto)

class ExchangeKeyReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXCHANGEKEYREQ
  
  # @@protoc_insertion_point(class_scope:ExchangeKeyReq)

class ExchangeKeyAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXCHANGEKEYACK
  
  # @@protoc_insertion_point(class_scope:ExchangeKeyAck)

class LoginReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINREQ
  
  # @@protoc_insertion_point(class_scope:LoginReq)

class HeartBeatAct(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARTBEATACT
  
  # @@protoc_insertion_point(class_scope:HeartBeatAct)

class ChallengeAct(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHALLENGEACT
  
  # @@protoc_insertion_point(class_scope:ChallengeAct)

# @@protoc_insertion_point(module_scope)
